name: Publish Docker Images on tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from Git tag
        id: extract
        run: |
          RAW_TAG=${GITHUB_REF#refs/tags/}       # v1.0.0
          VERSION=${RAW_TAG#v}                   # 1.0.0
          MINOR_VERSION=$(echo $VERSION | cut -d. -f1,2)  # 1.0
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MINOR=$MINOR_VERSION" >> $GITHUB_ENV

      - name: Build & Push PHP image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/php/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/php-symfony:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/php-symfony:${{ env.MINOR }}
            ghcr.io/${{ github.repository_owner }}/php-symfony:latest

      - name: Build & Push Nginx image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/nginx/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/nginx-symfony:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/nginx-symfony:${{ env.MINOR }}
            ghcr.io/${{ github.repository_owner }}/nginx-symfony:latest